Manager Class Reference
#include <manager.h>
Signals
void message (const QString &message)
Public Member Functions
Manager (QTcpServer *server, QObject *parent=0)
Private Slots
void newConnection ()
void processMessage (const QString &message)
Private Member Functions
QString parseMessage (const QString &m, QStringList *tokens)
Private Attributes
QHash< QString, ConnectionWrapper * > m_connections
QTcpServer * m_server
Detailed Description
Definition at line 9 of file manager.h.
Constructor & Destructor Documentation
Manager::Manager (QTcpServer * server, QObject * parent = 0)
Definition at line 8 of file manager.cpp.
References m_server, and newConnection().
9         :QObject(parent), m_server(server)
10 {
11     connect(m_server, SIGNAL(newConnection()),
12             this, SLOT(newConnection()));
13 }
Member Function Documentation
void Manager::message (const QString & message) [signal]
Referenced by newConnection(), and processMessage().
void Manager::newConnection () [private, slot]
Definition at line 15 of file manager.cpp.
References m_server, message(), and processMessage().
Referenced by Manager().
16 {
17     if (m_server->hasPendingConnections()) {
18         QTcpSocket* socket = m_server->nextPendingConnection();
19         ConnectionWrapper* w = new ConnectionWrapper(socket, this);
20         connect(w, SIGNAL(gotMessage(QString)),
21                 this, SLOT(processMessage(QString)));
22         connect(this, SIGNAL(message(QString)),
23                 w, SLOT(sendMessage(QString)));
24     }
25 }
QString Manager::parseMessage (const QString & m, QStringList * tokens) [private]
Definition at line 69 of file manager.cpp.
Referenced by processMessage().
70 {
71     tokens->clear();
72 
73     QStringList words = m.split(" ");
74     if (words.count() == 0)
75         return QString();
76 
77     QString command = words.takeAt(0).toUpper();
78     if (command == "NICK") { // NICK knows 2 arguments so take first 2
79         for (int i = 0; i < 2 && words.count() != 0; i++) {
80             tokens->append(words.takeAt(0));
81         }
82         return command;
83     } else if (command == "SAY") {
84         if (words.count() >= 2) { // SAY has 2 real arguments but n words
85             tokens->append(words.takeAt(0));
86             tokens->append(words.join(" "));
87             return command;
88         }
89     }
90 
91     return QString();
92 }
void Manager::processMessage (const QString & message) [private, slot]
Definition at line 27 of file manager.cpp.
References ConnectionWrapper::isRegistered(), m_connections, message(), ConnectionWrapper::nick(), parseMessage(), ConnectionWrapper::sendMessage(), ConnectionWrapper::setNick(), and ConnectionWrapper::setRegistered().
Referenced by newConnection().
28 {
29     ConnectionWrapper* c = qobject_cast<ConnectionWrapper*>(sender());
30     Q_ASSERT(c);
31 
32     QString m = msg.trimmed();
33     QString type;
34     QStringList tokens;
35     
36     qDebug() << m;
37     
38     type = parseMessage(m, &tokens);
39     if (type.isNull()) {
40         qDebug() << "Received invalid command!";
41         return;
42     }
43 
44     // For unregistered connections only NICK command is supported...
45     if (type == "NICK") {
46         QString nick = tokens[0];
47         if (c->isRegistered()) {
48             emit message(QString("NICK %1 %2").arg(nick).arg(c->nick()));
49         } else if (!c->isRegistered()){
50             c->sendMessage(QString("NICK %1").arg(nick));
51             m_connections[nick] = c;
52             c->setRegistered(true);
53             emit message(QString("STATUS %1 is now connected.").arg(nick));
54         }
55         c->setNick(nick);
56     }
57 
58     // ... but registered connections get the whole shebang, so bail now
59     // if the connection has not yet registered.
60     if (!c->isRegistered())
61         return;
62 
63     if (type == "SAY") {
64         QString toks = tokens.join(" ");
65         emit message(QString("SAY %1").arg(toks));
66     }
67 }
Member Data Documentation
QHash<QString, ConnectionWrapper*> Manager::m_connections [private]
Definition at line 26 of file manager.h.
Referenced by processMessage().
QTcpServer* Manager::m_server [private]
Definition at line 25 of file manager.h.
Referenced by Manager(), and newConnection().
The documentation for this class was generated from the following files:
manager.h
manager.cpp