Server Class Reference
#include <server.h>
Public Member Functions
virtual bool hasPendingConnections () const
virtual QTcpSocket * nextPendingConnection ()
Server (QObject *parent=0)
virtual ~Server ()
Protected Slots
void modeChanged (QSslSocket::SslMode mode)
void socketEncrypted ()
void socketError (QAbstractSocket::SocketError)
void sslError (const QList< QSslError > &errors)
void stateChanged (QAbstractSocket::SocketState socketState)
Protected Member Functions
virtual void incomingConnection (int socketDescriptor)
Private Attributes
QList< QSslSocket * > m_pendingConnections
Detailed Description
Definition at line 8 of file server.h.
Constructor & Destructor Documentation
Server::Server (QObject * parent = 0)
Definition at line 34 of file server.cpp.
References certificate(), and key().
34                               : QTcpServer(parent)
35 {
36     if (key.isNull())
37         qDebug() << "SSL key is null";
38     if (certificate.isNull())
39         qDebug() << "SSL cert is null";
40 }
Server::~Server () [virtual]
Definition at line 42 of file server.cpp.
References m_pendingConnections.
43 {
44     foreach(QSslSocket* s, m_pendingConnections) {
45         s->deleteLater();
46     }
47     m_pendingConnections.clear();
48 }
Member Function Documentation
bool Server::hasPendingConnections () const [virtual]
Definition at line 50 of file server.cpp.
References m_pendingConnections.
51 {
52     return m_pendingConnections.count() != 0;
53 }
void Server::incomingConnection (int socketDescriptor) [protected, virtual]
Definition at line 62 of file server.cpp.
References certificate(), key(), modeChanged(), socketEncrypted(), socketError(), sslError(), and stateChanged().
63 {
64     qDebug() << "Incoming connection";
65     QSslSocket* socket = new QSslSocket;
66     connect(socket, SIGNAL(encrypted()),
67             this, SLOT(socketEncrypted()));
68     connect(socket, SIGNAL(sslErrors(QList<QSslError>)),
69             this, SLOT(sslError(QList<QSslError>)));
70     connect(socket, SIGNAL(error(QAbstractSocket::SocketError)),
71             this, SLOT(socketError(QAbstractSocket::SocketError)));
72     connect(socket, SIGNAL(stateChanged(QAbstractSocket::SocketState)),
73             this, SLOT(stateChanged(QAbstractSocket::SocketState)));
74     connect(socket, SIGNAL(modeChanged(QSslSocket::SslMode)),
75             this, SLOT(modeChanged(QSslSocket::SslMode)));
76     socket->setPrivateKey(key);
77     socket->setLocalCertificate(certificate);
78     if (socket->setSocketDescriptor(socketDescriptor)) {
79         socket->startServerEncryption();
80         qDebug() << "Started server encryption";
81     } else {
82         qDebug() << "Could not set socket descriptor!";
83         socket->deleteLater();
84     }
85 }
void Server::modeChanged (QSslSocket::SslMode mode) [protected, slot]
Definition at line 87 of file server.cpp.
Referenced by incomingConnection().
88 {
89     qDebug() << mode;
90 }
QTcpSocket * Server::nextPendingConnection () [virtual]
Definition at line 55 of file server.cpp.
References m_pendingConnections.
56 {
57     QTcpSocket*s = m_pendingConnections.takeFirst();
58     s->disconnect();
59     return s;
60 }
void Server::socketEncrypted () [protected, slot]
Definition at line 113 of file server.cpp.
References m_pendingConnections.
Referenced by incomingConnection().
114 {
115     qDebug() << "socket encrypted";
116     QSslSocket* socket = qobject_cast<QSslSocket*>(sender());
117     if (socket) {
118         qDebug() << "Socket go!";
119         m_pendingConnections << socket;
120         emit newConnection();
121     }
122 }
void Server::socketError (QAbstractSocket::SocketError e) [protected, slot]
Definition at line 108 of file server.cpp.
Referenced by incomingConnection().
109 {
110     qDebug() << e;
111 }
void Server::sslError (const QList< QSslError > & errors) [protected, slot]
Definition at line 97 of file server.cpp.
Referenced by incomingConnection().
98 {
99     qDebug() << "SSL ERROR";
100     foreach(QSslError e, errors) {
101         qDebug() << e.error() << e.errorString();
102         if (e.error() == QSslError::NoPeerCertificate) {
103             qobject_cast<QSslSocket*>(sender())->ignoreSslErrors();
104         }
105     }
106 }
void Server::stateChanged (QAbstractSocket::SocketState socketState) [protected, slot]
Definition at line 92 of file server.cpp.
Referenced by incomingConnection().
93 {
94     qDebug() << socketState;
95 }
Member Data Documentation
QList<QSslSocket*> Server::m_pendingConnections [private]
Definition at line 28 of file server.h.
Referenced by hasPendingConnections(), nextPendingConnection(), socketEncrypted(), and ~Server().
The documentation for this class was generated from the following files:
server.h
server.cpp