ConnectionWrapper Class Reference
#include <connectionwrapper.h>
Public Slots
void sendMessage (const QString &message)
Signals
void gotMessage (const QString &message)
Public Member Functions
ConnectionWrapper (QTcpSocket *socket, QObject *parent=0)
bool isRegistered () const
QString nick () const
void setNick (QString nick)
void setRegistered (bool registered)
Protected Slots
void incoming ()
void stateChanged (QAbstractSocket::SocketState)
Private Attributes
QString m_nick
bool m_registered
QTcpSocket * m_socket
Detailed Description
Definition at line 9 of file connectionwrapper.h.
Constructor & Destructor Documentation
ConnectionWrapper::ConnectionWrapper (QTcpSocket * socket, QObject * parent = 0)
Definition at line 5 of file connectionwrapper.cpp.
References incoming(), m_socket, and stateChanged().
6                   :QObject(parent), m_socket(socket), m_registered(false)
7 {
8     connect(m_socket, SIGNAL(disconnected()),
9             this, SLOT(deleteLater()));
10     connect(m_socket, SIGNAL(readyRead()),
11             this, SLOT(incoming()));
12     connect(socket, SIGNAL(stateChanged(QAbstractSocket::SocketState)),
13             this, SLOT(stateChanged(QAbstractSocket::SocketState)));
14 }
Member Function Documentation
void ConnectionWrapper::gotMessage (const QString & message) [signal]
Referenced by incoming().
void ConnectionWrapper::incoming () [protected, slot]
Definition at line 22 of file connectionwrapper.cpp.
References gotMessage(), and m_socket.
Referenced by ConnectionWrapper().
23 {
24     while (m_socket->canReadLine()) {
25         QByteArray data = m_socket->readLine();
26         QString line = QString::fromUtf8(data.data(), data.size());
27         emit gotMessage(line);
28     }
29 }
bool ConnectionWrapper::isRegistered () const [inline]
Definition at line 14 of file connectionwrapper.h.
References m_registered.
Referenced by Manager::processMessage().
15         { return m_registered; }
QString ConnectionWrapper::nick () const [inline]
Definition at line 18 of file connectionwrapper.h.
References m_nick.
Referenced by Manager::processMessage().
19         { return m_nick; }
void ConnectionWrapper::sendMessage (const QString & message) [slot]
Definition at line 16 of file connectionwrapper.cpp.
References m_socket.
Referenced by Manager::processMessage().
17 {
18     m_socket->write(message.toUtf8());
19     m_socket->write(QString("\n").toUtf8());
20 }
void ConnectionWrapper::setNick (QString nick) [inline]
Definition at line 20 of file connectionwrapper.h.
References m_nick.
Referenced by Manager::processMessage().
21         { m_nick = nick; }
void ConnectionWrapper::setRegistered (bool registered) [inline]
Definition at line 16 of file connectionwrapper.h.
References m_registered.
Referenced by Manager::processMessage().
17         { m_registered = registered; }
void ConnectionWrapper::stateChanged (QAbstractSocket::SocketState state) [protected, slot]
Definition at line 31 of file connectionwrapper.cpp.
Referenced by ConnectionWrapper().
32 {
33     if (state == QAbstractSocket::ClosingState) {
34         deleteLater();
35     }
36 }
Member Data Documentation
QString ConnectionWrapper::m_nick [private]
Definition at line 36 of file connectionwrapper.h.
Referenced by nick(), and setNick().
bool ConnectionWrapper::m_registered [private]
Definition at line 35 of file connectionwrapper.h.
Referenced by isRegistered(), and setRegistered().
QTcpSocket* ConnectionWrapper::m_socket [private]
Definition at line 34 of file connectionwrapper.h.
Referenced by ConnectionWrapper(), incoming(), and sendMessage().
The documentation for this class was generated from the following files:
connectionwrapper.h
connectionwrapper.cpp